# .github/workflows/qodana_code_quality.yml
name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      # Ensure ESLint & plugins are available to Qodana
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm # or: yarn / pnpm
      - run: npm ci   # or: yarn --frozen-lockfile / pnpm i --frozen-lockfile

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.2
        with:
          args: --show-report
          # project-dir: ./apps/web   # uncomment if your app lives in a subfolder
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_551844708 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
